version: "3.7"
services:
        mysql:
                image: "mysql:latest"
                restart: always
                ports:
                        - "3306:3306"
                volumes:
                    - "mydata:/var/lib/mysql"
                network_mode: bridge
                environment:
                    MYSQL_ROOT_PASSWORD: root    

volumes:
        mydata: {}

   
